### ISSUE TITLE
Do we need a `.stylelintignore` with @workleap/stylelint-config?

### ISSUE THREAD

**Issue by ofrogon** [workleap/wl-web-configs#39]
There is no mention of `.stylelintignore` in [@workleap/stylelint-config README.md](https://github.com/workleap/wl-web-configs/blob/main/packages/stylelint-config/README.md), do we need this file to be sure StyleLint doesn't interfere with EsLint?

As a note also, it is worth mentioning that .stylelintignore acts differently than normal .ignore files as of:
```
*
!**/*.css
```
will not work and will just ignore everything.

**Comment by alexasselin008** [comment]
Stylelint ignore should not be required for our projects. Historically, we had that because there was an issue with the extension we were using. But the problem is no longer present in the Stylelint extensions. We should however add the recommended extension `stylelint.vscode-stylelint` to `.vscode/extensions.json` for projects that use CSS. 

We should avoid using stylelint-plus going forward
